### ISSUE TITLE
由于天翼客户端心跳包机制代码有bug引起的频繁掉线问题

### ISSUE THREAD

**Issue by Clovin** [ZSCNetSupportDept/wiki#5]
表现： 登录成功后20分钟左右掉线，错误代码如下图

![8ca39f0a3d33bd3ac56f2ea97447cd69](https://user-images.githubusercontent.com/16433817/40959667-f55593c2-68cf-11e8-81d1-ea9676f3fdc3.png)

解决方案：将账号后缀删除

原因： 心跳包的代码和登录页面的代码不同，登录页面的代码登录可以正常解析后缀，心跳包的代码没法正常解析后缀，导致后续验证失败。

**Comment by FsHtroy** [comment]
Please check #6

**Comment by FsHtroy** [comment]
Merged in commit #0ce8acb.
Thank you.
